name: "Health Platform Testing"
on push:
  branch: main
runs:
  - name: Setup Node.js, Register packages install extensions
    run : 'npm install installext handle test run steps means run node test start compressed files and standard the standards  test ingredients  only that the check funcctionality performs in the link all days.
  - name: Register test outputs .case
