name: "Health Platform Testing"
on push:
  branch: main
jobs:
  - name: Run jstest with node.js
  run: node.js 16, npm install audit fix --force
steps:
  - name: Install dependencies and perform test
    run: npm install espress node.js --production
