name: "Health Platform Testing"
on push:
  branch: main
jobs:
  - name: Run jstest with node.js
  run: node.js 12, npm install test start
config:
  test type: lengthy long
steps:
  - name: Install packages and dopeundencies
    run: npm install express fs node.js
  - name: Run unit tests and api endpoints
    run: npm test --restore formatCover</style>
